// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTuGHcQW0XFjUBChsAAlTZwHoQa1hOMhk',
    appId: '1:930694187507:android:c4a5e126621a8e1a82aa86',
    messagingSenderId: '930694187507',
    projectId: 'flighterr-6b626',
    storageBucket: 'flighterr-6b626.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApEuidHC50QR6f2ufMxPaGu8vKp8yL6Jc',
    appId: '1:930694187507:ios:95abb214f795504d82aa86',
    messagingSenderId: '930694187507',
    projectId: 'flighterr-6b626',
    storageBucket: 'flighterr-6b626.appspot.com',
    androidClientId: '930694187507-02286u3ctsa2onic66vgt5jgd0ses0ph.apps.googleusercontent.com',
    iosClientId: '930694187507-r0brouscjbpieggv34ptsvgcjcq4i4um.apps.googleusercontent.com',
    iosBundleId: 'com.example.flighterr',
  );
}
